replicaCount: 2

image:
  repository: karty11/newbankapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

mssql:
  host: mssql.mssql.svc.cluster.local
  port: 1433
  dbname: analytics

  ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: java-backend.192.168.2.5.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []


resources: {}
