image:
  repository: docker.io/karty11/newbankapp
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: public
  host: demo.local
  path: /
