apiVersion: v1
kind: Namespace
metadata:
  name: mssql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: mssql
spec:
  serviceName: mssql
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-sa-secret
                  key: SA_PASSWORD
          ports:
            - containerPort: 1433
          readinessProbe:
            # simple TCP probe to port 1433
            tcpSocket:
              port: 1433
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
            - name: mssqldata
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: mssqldata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: mssql
spec:
  clusterIP: None
  ports:
    - port: 1433
      name: mssql
  selector:
    app: mssql
