apiVersion: batch/v1
kind: Job
metadata:
name: vault-init
namespace: vault
spec:
template:
spec:
serviceAccountName: default
containers:
- name: vault-init
image: curlimages/curl:7.88.1
env:
- name: VAULT_ADDR
value: "http://vault.vault.svc.cluster.local:8200"
- name: VAULT_TOKEN
valueFrom:
secretKeyRef:
name: vault-root
key: token
command: ["/bin/sh", "
