apiVersion: v1
kind: Service
metadata:
name: {{ include "java-backend.fullname" . }}
labels:
app: {{ include "java-backend.name" . }}
spec:
type: {{ .Values.service.type }}
ports:
- port: {{ .Values.service.port }}
targetPort: 8080
protocol: TCP
selector:
app: {{ include "java-backend.name" . }}
