apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/karty11/demo_microk8s.git'  
    targetRevision: HEAD
    path: charts/java-backend
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
