name: CD Pipeline - Deploy to MicroK8s via ArgoCD and Helm

on:
  workflow_dispatch:
    paths:
      - charts/**
      - argocd/**

jobs:
  cd-deploy:
    name: Continuous Deployment to MicroK8s
    runs-on: self-hosted

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sync kubeconfig from MicroK8s VM (ensures latest IP/config)
      - name: Sync kubeconfig from MicroK8s VM
        run: |
          mkdir -p ~/.kube
          multipass exec microk8s-vm -- microk8s config > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl get nodes

      # Step 3: Verify Kubernetes context
      - name: Verify kube context
        run: |
          kubectl config current-context
          kubectl cluster-info

      # Step 4: Install ArgoCD CLI (cross-platform safe)
      - name: Install ArgoCD CLI
        run: |
          set -e
          ARCH=$(uname -m)
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')

          echo "Detected OS: $OS, Arch: $ARCH"

          # Pick correct binary
          if [[ "$OS" == "darwin" && "$ARCH" == "arm64" ]]; then
            URL="https://github.com/argoproj/argo-cd/releases/latest/download/argocd-darwin-arm64"
          elif [[ "$OS" == "darwin" ]]; then
            URL="https://github.com/argoproj/argo-cd/releases/latest/download/argocd-darwin-amd64"
          else
            URL="https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64"
          fi

          echo "Downloading ArgoCD CLI from: $URL"
          curl -sSL -o /tmp/argocd "$URL"
          chmod +x /tmp/argocd

          # Install to a writable path (no sudo needed)
          mkdir -p ~/.local/bin
          mv /tmp/argocd ~/.local/bin/argocd
          export PATH="$HOME/.local/bin:$PATH"

          echo "Verifying installation..."
          ~/.local/bin/argocd version --client

      # Step 5: Log in to ArgoCD
      - name: Log in to ArgoCD
        run: |
          ~/.local/bin/argocd login ${{ secrets.ARGOCD_SERVER }} \
            --username admin \
            --password "${{ secrets.ARGOCD_PASSWORD }}" \
            --insecure

      # Step 6: Apply ArgoCD Application manifest
      - name: Apply ArgoCD application manifest
        run: |
          kubectl apply -f argocd/app.yaml
          echo "ArgoCD Application manifest applied."

      # Step 7: Sync and Wait for Application
      - name: Sync and Wait for Application
        run: |
          ~/.local/bin/argocd app sync demo-app --timeout 300
          ~/.local/bin/argocd app wait demo-app --health --timeout 300

      # Step 8: Verify Deployment in MicroK8s
      - name: Verify deployment in MicroK8s
        run: |
          kubectl get pods -n demo-app
          kubectl get svc -n demo-app
          kubectl get ingress -n demo-app
