name: CD - Deploy to microk8s (CSI + AWS Secrets)

on:
  workflow_dispatch:  # <-- manual trigger only

jobs:
  deploy:
    runs-on: self-hosted
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Install Helm manually (macOS)
       run: |
         brew install helm
   
     - name: Verify Helm & Kubectl
       run: |
        kubectl version --client
        helm version

     - name: Install CSI Secrets Store Driver
       run: |
        helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
        helm repo update

        helm upgrade --install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver \
         --namespace kube-system --create-namespace \
         --set enableSecretRotation=true \
         --set rotationPollInterval="1h" \
         --wait --timeout 5m

          
     - name: Install AWS provider (ASCP)
       run: |
        helm repo add aws-secrets-manager
        https://aws.github.io/secrets-store-csi-driver-provider-aws

        helm repo update

        helm upgrade --install csi-secrets-provider-aws aws-secrets-manager/secrets-store-csi-driver-provider-aws \
         --namespace kube-system --wait --timeout 5m
     
     - name: Install Stakater Reloader
       run: |
         helm repo add stakater https://stakater.github.io/stakater-helm3
         helm repo update
         helm upgrade --install reloader stakater/reloader \
          --namespace kube-system --create-namespace \
          --wait --timeout 5m    
         
     - name: Create provider ServiceAccount & (fallback) AWS creds secret
       run: |
        kubectl apply -f infra/aws-csi/sa-aws-provider.yaml

     - name: secrets
       run: |
        kubectl create namespace mssql || true
        kubectl create secret generic mssql-sa-secret \
         --from-literal=SA_PASSWORD='YourStrong!Passw0rd' \
         -n mssql
  

      # If running outside EKS, optionally create aws-creds secret (DO NOT store real creds in repo)

      # kubectl apply -f infra/aws-csi/aws-creds-secret-example.yaml
     - name: Deploy MSSQL (dev/test)
       run: |
        kubectl apply -f infra/mssql/mssql-statefulset.yaml
     - name: Apply SecretProviderClass (mount AWS secret bankapp/mysql)
       run: |
         kubectl apply -f infra/aws-csi/secretproviderclass.yaml
     - name: Create ArgoCD Application for java-backend
       run: |
         kubectl apply -f infra/argocd/app-java-backend.yaml
     - name: Show pods
       run: |
         kubectl get pods --all-namespaces -o wide

     - name: Validate AWS secret mount via test pod
       run: |
         kubectl apply -f infra/aws-csi/test-pod.yaml
         kubectl wait --for=condition=Ready pod/aws-secret-test --timeout=60s
         kubectl exec -it aws-secret-test -- ls /mnt/secrets
         kubectl exec -it aws-secret-test -- cat /mnt/secrets/SPRING_DATASOURCE_USERNAME
         kubectl delete pod aws-secret-test     
